CC=x86_64-w64-mingw32-gcc
CFLAGS=`x86_64-w64-mingw32-sdl2-config --cflags` -Wall -Wextra -std=c11
LDFLAGS=`x86_64-w64-mingw32-sdl2-config --libs` -lSDL2_image -lSDL2_mixer -lSDL2_ttf
TARGET=candycrush.exe

all: $(TARGET)

$(TARGET): main.o
	$(CC) main.o -o $(TARGET) $(LDFLAGS)

main.o: main.c
	$(CC) $(CFLAGS) -c main.c

clean:
	rm -f $(TARGET) *.o
